name: Benchmark runner

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6.14
      - run: pnpm --dir=benchmarks install
      - run: pnpm --dir=benchmarks run benchmark
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "chore: update benchmarks"
          branch: main
