name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ["Benchmark runner"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - name: Checkout Commit
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install pnpm
      run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@next
    - name: Install dependencies
      run: pnpm install
    - name: Update pnpm bundle
      run: curl -L --fail https://get.pnpm.io/v5.js > static/pnpm.js
    - uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
    - name: Release to GitHub Pages
      env:
        USE_SSH: true
        GIT_USER: git
        DEPLOYMENT_BRANCH: master
      run: |
        git config --global user.email "yuchao.dev@gmail.com"
        git config --global user.name "cuyl"
        pnpm copy-docs
        pnpm deploy
